services:
  laravel:
    build: .
    restart: unless-stopped
    container_name: laravel
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - laravel-network

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bitnami_myapp
      - MYSQL_USER=bn_myapp
      - MYSQL_PASSWORD=secret
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel-network
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite # Dockerfile for Vite
    volumes:
      - ./:/app
      - vite_node_modules:/app/node_modules
    ports:
      - "5173:5173" # Expose Vite’s port (optional for direct access)
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - laravel
    environment:
      - VITE_HOST=0.0.0.0

volumes:
  mariadb_data:
  vite_node_modules:


networks:
  laravel-network:
