services:
  app:
    build: .
    container_name: laravel
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bitnami_myapp
      - MYSQL_USER=bn_myapp
      - MYSQL_PASSWORD=secret
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  mariadb_data:


networks:
  laravel-network:
