services:
  laravel:
    build: .
    restart: unless-stopped
    container_name: laravel
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - laravel-network

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bitnami_myapp
      - MYSQL_USER=bn_myapp
      - MYSQL_PASSWORD=secret
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel-network
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    volumes:
      - ./:/app
      - vite_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Fixes HMR websocket connections
      - VITE_HMR_HOST=localhost
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  mariadb_data:
  vite_node_modules:


networks:
  laravel-network:
